### ISSUE TITLE
cfg(feature) on two identical lines

### ISSUE THREAD

**Issue by BRA1L0R** [leshow/rotary-encoder-hal#18]
https://github.com/leshow/rotary-encoder-hal/blob/098002590722f985b6782b7130e8dfd4bef7e8a2/src/lib.rs#L95-L98

they are identical but still separated by a cfg attribute

**Comment by leshow** [comment]
git blame says that the second line used to use `try_is_low`. I would guess when the API change it slipped through unnoticed.

**Comment by leshow** [comment]
I believe #20 includes this
