### ISSUE TITLE
Add CI 

### ISSUE THREAD

**Issue by leshow** [leshow/rotary-encoder-hal#4]
`rotary-encoder-hal` currently has no CI. Would be nice to have a CI that runs  rustfmt, clippy, cargo doc, and cargo test. 

Bonus if it compiles on other toolchains also like `thumbv7m-none-eabi`

**Comment by PurpleMyst** [comment]
I'm willing to work on this. Which CI platform would you prefer? (GitHub Actions, CircleCI, Travis CI, something else..?)

**Comment by leshow** [comment]
Hey! I'll just link my other comment here: https://github.com/leshow/tokio-i3ipc/issues/12#issuecomment-702803651

with the caveat we have to also build on common ARM targets:
e.i
```
    Use thumbv6m-none-eabi for ARM Cortex-M0 and Cortex-M0+
    Use thumbv7m-none-eabi for ARM Cortex-M3
    Use thumbv7em-none-eabi for ARM Cortex-M4 and Cortex-M7 (no FPU support)
    Use thumbv7em-none-eabihf for ARM Cortex-M4F and Cortex-M7F (with FPU support)
```
(quoted from cortex-m-quickstart)

There's a PR already with an example in it too, we can add that as well, but feel free to throw out the travis related stuff

**Comment by PurpleMyst** [comment]
We can cross-compile to those targets, however I'm not sure what else we could do? We could try using something like `qemu`  to run the tests?

**Comment by leshow** [comment]
Yeah good point, don't worry about qemu, just the cross-compile should be fine. I'd prefer to use github actions on this one, all things being equal, if you don't mind.

**Comment by PurpleMyst** [comment]
Alright, I'll work on this then.

**Comment by PurpleMyst** [comment]
I'm working on this, but could I ask you to had the hacktoberfest topic to the repo so that it gets counted in my contributions? 😄

**Comment by leshow** [comment]
Sure, no problem
